server:
  port: 8082
  error:
    include-stacktrace: always

# gRPC server configuration
grpc:
  server:
    port: 6792
    # Turn on the service listing (for both actuator and grpc)
    reflection-service-enabled: true

spring:
  config:
    location: classpath:/application-dev.yml
  banner:
    location: classpath:/dev/banner.txt

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        # exposing all endpoints
        include: "*"
