server:
  port: 8080

# gRPC server configuration
grpc:
  server:
    port: 6565
    # Turn off the service listing (for both actuator and grpc)
    reflection-service-enabled: off

spring:
  config:
    location: classpath:/application-prod.yml
  banner:
    location: classpath:/prod/banner.txt

  # Mongo properties
  data:
    mongodb:
      host: mongodb

  # Kafka properties
  kafka:
    producer:
      bootstrap-servers: kafka-1:9092

# Actuator configuration
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        # exposed endpoints
        include: health, info, prometheus