server:
  port: 8083

# gRPC server configuration
grpc:
  server:
    port: 6568
    # Turn off the service listing (for both actuator and grpc)
    reflection-service-enabled: off

spring:
  config:
    location: classpath:/application-prod.yml
  banner:
    location: classpath:/prod/banner.txt

  # Mongo properties
  data:
    mongodb:
      host: mongodb

  # Kafka properties
  kafka:
    producer:
      bootstrap-servers: kafka-1:9093,kafka-2:9094,kafka-3:9095

# Actuator configuration
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        # exposed endpoints
        include: health, info, prometheus

# OpenApi configuration
api:
  dev:
    server:
      base-url: http://localhost${server.servlet.context-path}
  prod:
    server:
      base-url: http://localhost${server.servlet.context-path}
