server:
  compression:
    enabled: true
  servlet:
    context-path: /api
  tomcat:
    threads:
      max: 100
  http2:
    # Enables http2 support
    enabled: true
  error:
    # Includes error attribute to message response
    include-message: always
    include-binding-errors: always

spring:
  profiles:
    active: '@spring.profiles.active@'

  main:
    allow-bean-definition-overriding: true

  jmx:
    enabled: false

  # Mongo properties
  data:
    mongodb:
      port: 27017
      database: rpsDB
      username: root
      password: mongo12345
      authentication-database: admin # name of the authentication database
      auto-index-creation: true # enable auto index creation

  # Jackson properties
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      INDENT_OUTPUT: true
    time-zone: UTC

  # Kafka properties
  kafka:
    producer:
      client-id: '@project.artifactId@'
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: all

# Actuator configuration
management:
  # context path  /api/actuator
  server:
    base-path: ${server.servlet.context-path}
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

# Open Api 3.0 configuration
springdoc:
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    use-root-path: true
  # packages to include
  packages-to-scan: com.al.qdt.score.cmd.api
  # enables pretty-printed output of the OpenApi specification
  writer-with-default-pretty-printer: true

# OpenApi configuration
api:
  dev:
    server:
      description: Dev server
      base-url: http://localhost:8082${server.servlet.context-path}
  prod:
    server:
      description: Prod server
      base-url: http://localhost:8080${server.servlet.context-path}
  endpoint-scores: scores
  version-one: /v1
  version-one-async: /v1.1
  version-two: /v2
  version-two-async: /v2.1
  license-name: The GNU General Public License, Version 3
  license-url: https://www.gnu.org/licenses/gpl-3.0.txt

# Application configuration
app:
  # Executor configuration
  executor:
    core-pool-size: 2
    max-pool-size: 2
    queue-capacity: 500
    thread-name-prefix: async-thread
  # Kafka configuration
  kafka:
    max-in-flight-request-per-connection: 1
    is-idempotence-enabled: true
