server:
  port: 8080

grpc:
  server:
    port: 6792

spring:
  config:
    location: classpath:/application-it.yml
  banner:
    location: classpath:/it/banner.txt

  # Mongo properties
  data:
    mongodb:
      host: localhost

  # Kafka properties
  kafka:
    producer:
      bootstrap-servers: localhost:9092
