server:
  compression:
    enabled: true
  servlet:
    context-path: /api
  tomcat:
    threads:
      max: 100
  error:
    # Includes error attribute to message response
    include-message: always
    include-binding-errors: always

spring:
  profiles:
    active: '@spring.profiles.active@'

  main:
    allow-bean-definition-overriding: true

  jmx:
    enabled: false

  # Mongo properties
  data:
    mongodb:
      host: localhost
      port: 27017
      database: rpsDB
      username: root
      password: mongo12345
      authentication-database: admin # name of the authentication database
      auto-index-creation: true # enable auto index creation

  # Jackson properties
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      INDENT_OUTPUT: true
    time-zone: UTC

  # Kafka properties
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3

# Actuator configuration
management:
  # context path  /api/actuator
  server:
    base-path: ${server.servlet.context-path}
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        # exposing endpoints
        include: prometheus
  info:
    git:
      mode: full

# Open Api 3.0 configuration
springdoc:
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    use-root-path: true
  # packages to include
  packages-to-scan: com.al.qdt.score.cmd.api
  # enables pretty-printed output of the OpenApi specification
  writer-with-default-pretty-printer: true

api:
  dev:
    server:
      description: Dev server
      base-url: http://localhost:8082${server.servlet.context-path}
  prod:
    server:
      description: Prod server
      base-url: http://localhost:8080${server.servlet.context-path}
  endpoint-scores: scores
  version-one: /v1
  version-two: /v2
  license-name: The GNU General Public License, Version 3
  license-url: https://www.gnu.org/licenses/gpl-3.0.txt
