server:
  port: 8081

# gRPC server configuration
grpc:
  server:
    port: 6566
    # Turn off the service listing (for both actuator and grpc)
    reflection-service-enabled: off

spring:
  config:
    location: classpath:/application-docker.yml
  banner:
    location: classpath:/docker/banner.txt

  # Mongo properties
  data:
    mongodb:
      host: mongodb

  # Kafka properties
  kafka:
    producer:
      bootstrap-servers: kafka-1:9093,kafka-2:9094,kafka-3:9095

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        # exposing all endpoints
        include: "*"
  endpoint:
    health:
      show-details: always

# OpenApi configuration
api:
  dev:
    server:
      base-url: http://host.docker.internal${server.servlet.context-path}
  prod:
    server:
      base-url: http://host.docker.internal${server.servlet.context-path}
