server:
  port: 8080
  error:
    include-stacktrace: always

# gRPC server configuration
grpc:
  server:
    port: 6790
    # Turn on the service listing (for both actuator and grpc)
    reflection-service-enabled: true

spring:
  config:
    location: classpath:/application-dev.yml
  banner:
    location: classpath:/dev/banner.txt

  # Mongo properties
  data:
    mongodb:
      host: localhost

  # Kafka properties
  kafka:
    producer:
      bootstrap-servers: localhost:9092

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        # exposing all endpoints
        include: "*"
  endpoint:
    health:
      show-details: always
