server:
  port: 8080

grpc:
  server:
    port: 6790

spring:
  config:
    location: classpath:/application-it.yml
  banner:
    location: classpath:/it/banner.txt

  # Mongo properties
  data:
    mongodb:
      host: localhost

  # Kafka properties
  kafka:
    producer:
      bootstrap-servers: localhost:9093,localhost:9094,localhost:9095

# OpenApi configuration
api:
  dev:
    server:
      base-url: http://localhost:8081${server.servlet.context-path}
  prod:
    server:
      base-url: http://localhost:8080${server.servlet.context-path}
