server:
  port: 8083
  error:
    include-stacktrace: always

# gRPC server configuration
grpc:
  server:
    port: 6793
    # Turn on the service listing (for both actuator and grpc)
    reflection-service-enabled: true

spring:
  config:
    location: classpath:/application-dev.yml
  banner:
    location: classpath:/dev/banner.txt

  jpa:
    # show log for each sql query
    show-sql: true
    hibernate:
      # schema will be automatically created afresh for every start of the application
      ddl-auto: update
    # allows Hibernate to generate SQL optimized for a particular DBMS
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    defer-datasource-initialization: false
    properties:
      hibernate:
        # format sql query
        format_sql: true

  # MariaDB database connection configuration
  datasource:
    url: jdbc:mariadb://localhost:3306/scoreDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 12345
    driver-class-name: org.mariadb.jdbc.Driver

  # Flyway configuration
  flyway:
    url: jdbc:mariadb://localhost:3306
    user: root
    password: 12345
    schemas: scoreDB

  # Kafka properties
  kafka:
    consumer:
      bootstrap-servers: localhost:9093,localhost:9094,localhost:9095

  # Cache configuration
  cache:
    type: redis
    redis:
      cache-null-values: true

  # Redis configuration
  redis:
    host: localhost
    password: 12345
    port: 6379

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        # exposing all endpoints
        include: "*"
  endpoint:
    health:
      show-details: always

# Show bind values
logging.level.org.hibernate.type.descriptor.sql: trace
