server:
  port: 8082

# gRPC server configuration
grpc:
  server:
    port: 6567
    # Turn off the service listing (for both actuator and grpc)
    reflection-service-enabled: off

spring:
  config:
    location: classpath:/application-docker.yml
  banner:
    location: classpath:/docker/banner.txt

  jpa:
    # show log for each sql query
    show-sql: true
    # schema will be automatically created afresh for every start of the application
    hibernate:
      ddl-auto: update
    # allows Hibernate to generate SQL optimized for a particular DBMS
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    defer-datasource-initialization: false
    properties:
      hibernate:
        # format sql query
        format_sql: true

  # MariaDB database connection configuration
  datasource:
    url: jdbc:mariadb://mariadb:3306/rpsDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 12345
    driver-class-name: org.mariadb.jdbc.Driver

  # Flyway configuration
  flyway:
    url: jdbc:mariadb://mariadb:3306
    user: root
    password: 12345
    schemas: rpsDB

  # Kafka properties
  kafka:
    consumer:
      bootstrap-servers: kafka-1:9093,kafka-2:9094,kafka-3:9095

  # Cache configuration
  cache:
    type: redis
    redis:
      cache-null-values: true

  # Redis configuration
  redis:
    host: redis
    password: 12345
    port: 6379

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        # exposing all endpoints
        include: "*"
  endpoint:
    health:
      show-details: always

# OpenApi configuration
api:
  dev:
    server:
      base-url: http://host.docker.internal${server.servlet.context-path}
  prod:
    server:
      base-url: http://host.docker.internal${server.servlet.context-path}
