server:
  port: 8081
  error:
    include-stacktrace: always

# gRPC server configuration
grpc:
  server:
    port: 6791
    # Turn on the service listing (for both actuator and grpc)
    reflection-service-enabled: true

spring:
  config:
    location: classpath:/application-dev.yml
  banner:
    location: classpath:/dev/banner.txt

  jpa:
    # show log for each sql query
    show-sql: true
    hibernate:
      # schema will be automatically created afresh for every start of the application
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    properties:
      hibernate:
        # format sql query
        format_sql: true

  datasource:
    url: jdbc:h2:mem:rpsDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: root
    password: 12345
    driver-class-name: org.h2.Driver

  h2:
    # enables h2 console at http://localhost:8081/api/h2-console
    console:
      enabled: true
      # relative path to the console
      path: /h2-console
      settings:
        # disable remote access
        web-allow-others: false
        # prevent trace output
        trace: false

  kafka:
    consumer:
      bootstrap-servers: localhost:9092

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        # exposing all endpoints
        include: "*"

# Show bind values
logging.level.org.hibernate.type.descriptor.sql: trace
