server:
  port: 8080

grpc:
  server:
    port: 6791

spring:
  config:
    location: classpath:/application-it.yml
  banner:
    location: classpath:/it/banner.txt

  jpa:
    # show log for each sql query
    show-sql: true
    hibernate:
      # schema will be automatically created afresh for every start of the application
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    properties:
      hibernate:
        # format sql query
        format_sql: true

  datasource:
    url: jdbc:h2:mem:rpsDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: root
    password: 12345
    driver-class-name: org.h2.Driver

  h2:
    # enables h2 console at http://localhost:8080/h2-console
    console:
      enabled: true
      # relative path to the console
      path: /h2-console
      settings:
        # disable remote access
        web-allow-others: false
        # prevent trace output
        trace: false

  # Flyway configuration
  flyway:
    enabled: false

  # Kafka properties
  kafka:
    consumer:
      bootstrap-servers: localhost:9093,localhost:9094,localhost:9095

  # Cache configuration
  cache:
    type: simple
